export const KP_RITUALS = [
  {
    id: 'devgon',
    name: 'Devgon',
    kashmiri: 'देवगन',
    category: 'Annual Ritual',
    description: 'Annual propitiation of ancestors and household deities. A uniquely Kashmiri Pandit ritual performed annually in the home.',
    purpose: 'To honor and seek blessings from the family deity (Kuldevta/Kuldevi) and ancestors. To renew the spiritual protection of the household.',
    historicalBackground: 'Devgon is rooted in the ancient Kashmiri tradition of ancestor worship combined with Shaiva tantra. It predates the arrival of Vaishnava traditions in Kashmir.',
    religiousSignificance: 'Maintains the sacred covenant between the family and its protecting deities. Ensures continued blessings and protection for the household.',
    materials: [
      'Thaal (ritual plate) with specific items',
      'Walnuts (akhrot)',
      'Rice (chawal)',
      'Mustard oil lamp (diwa)',
      'Incense (agarbatti)',
      'Red cloth',
      'Flowers (especially marigold)',
      'Betel leaves and nuts',
      'Fruit offerings',
      'Curd (dahi)',
      'Honey (shahad)',
    ],
    steps: [
      'Purification of the puja space (shodhana)',
      'Preparation of the ritual thaal',
      'Invocation of family deity through specific mantras',
      'Offering of water, flowers, food',
      'Recitation of family-specific prayers',
      'Seeking blessings for all family members',
      'Distribution of prasad',
    ],
    regionalVariations: 'Devgon procedures vary significantly by family and region within Kashmir. Some families perform elaborate multi-day rituals while others have simpler traditions.',
    commonMisconceptions: 'Devgon is not simply a generic puja — it is a family-specific ritual with unique elements passed down through generations.',
    icon: '🪔',
  },
  {
    id: 'lagan',
    name: 'Lagan',
    kashmiri: 'लगन',
    category: 'Marriage Ceremony',
    description: 'The Kashmiri Pandit marriage — from the formal engagement (Lagan Patra) through the sacred wedding rites. Lagan is among the most elaborate and distinctive ceremonies in Hindu tradition, blending Vedic Brahminical rites with Kashmir Shaiva philosophy.',
    purpose: 'Sacred union of two souls and two families, solemnised through ancient Vedic and Kashmiri Shaiva rites — beginning with astrological matching and the fixing of the auspicious muhurat, and culminating in the wedding.',
    historicalBackground: 'Lagan has been practised for centuries in Kashmiri Pandit communities, combining astrology, family approval, and a sequence of ritual elements unique to Kashmir and not found in other Hindu wedding traditions.',
    religiousSignificance: 'Marriage is considered a sacred duty (dharma) and a spiritual journey for both partners. It opens with kundali milan (astrological matching) and the formal Lagan Patra, and proceeds through the sacred fire rites.',
    materials: [
      'Lagan Patra (formal engagement letter)',
      'Ritual fire (havan kund)',
      'Ghee for havan',
      'Devgon thaal items',
      'Mout (crown) for bride and groom',
      'Dejhoor (earrings)',
      'Aetpar (special rice balls)',
      'Kadur (ring)',
      'Coconut, Supari (betel nut), flowers',
      'Ceremonial garments',
    ],
    steps: [
      'Consultation with astrologer/pandit for muhurat (kundali milan)',
      'Preparation and exchange of Lagan Patra between families',
      'Livun (ritual purification of the venue)',
      'Devgon by both families',
      'Mehndi ceremony',
      'Yagnopavit ceremony for groom (if not already done)',
      'Vara Chaturdashi (day before the wedding)',
      'Panigrahana (sacred union rites)',
      'Pheras (rounds around the sacred fire) and Saptapadi',
      'Gouri Puja by the bride',
      'Reception ceremonies',
    ],
    regionalVariations: 'Significant variations exist between families from different tehsils and villages in Kashmir.',
    commonMisconceptions: 'Lagan is a binding commitment, not merely an informal engagement, and KP weddings are distinct from North Indian Hindu weddings in many ritual elements.',
    icon: '🕉️',
  },
  {
    id: 'yagnopavit',
    name: 'Yagnopavit (Janeu Ceremony)',
    kashmiri: 'यज्ञोपवीत',
    category: 'Samskara',
    description: 'The sacred thread ceremony marking a Kashmiri Pandit boy\'s entry into the stage of student life (brahmacharya).',
    purpose: 'Initiation into Brahmin life and the beginning of Vedic education.',
    historicalBackground: 'One of the sixteen samskaras (rites of passage), Yagnopavit has been central to KP identity.',
    religiousSignificance: 'The sacred thread (yagnopavit) represents the three debts owed to the divine, ancestors, and teachers.',
    materials: [
      'Sacred thread (three strands)',
      'Kashmiri mudra',
      'Ritual items for havan',
      'New dhoti and kurta',
      'Mout (crown)',
      'Danda (staff)',
      'Kamandalu (water pot)',
      'Begging bowl (symbolic)',
    ],
    steps: [
      'Preparation and purification',
      'Mundan (head shaving) if done together',
      'Havan',
      'Investment of sacred thread by father',
      'Gayatri Mantra initiation',
      'Symbolic begging from mother',
      'Departure ceremony (symbolic)',
      'Family feast',
    ],
    regionalVariations: 'Traditionally performed at age 7-12, though now often a single-day ceremony.',
    commonMisconceptions: 'Yagnopavit is not merely symbolic — it carries deep spiritual responsibility.',
    icon: '🧵',
  },
  {
    id: 'mundan',
    name: 'Mundan (Chudakarana)',
    kashmiri: 'मुंडन',
    category: 'Samskara',
    description: 'The first haircut ceremony for a KP child, typically in the first or third year.',
    purpose: 'Removal of birth hair, symbolizing purification and new beginning.',
    historicalBackground: 'Among the Shodasha Samskaras, Mundan has been observed in KP families for generations.',
    religiousSignificance: 'The first hair is believed to carry karmic impurities from the previous birth. Its removal purifies the child.',
    materials: [
      'New razor (traditional)',
      'Ritual items for puja',
      'Flowers',
      'Sweets for distribution',
    ],
    steps: [
      'Selection of auspicious date',
      'Morning puja',
      'The cutting ceremony',
      'Hair offered to sacred river or buried',
      'Distribution of sweets',
      'Family celebration',
    ],
    regionalVariations: 'Some families perform Mundan at family temples or sacred sites.',
    commonMisconceptions: 'Mundan is a sacred rite, not just a haircut.',
    icon: '✂️',
  },
  {
    id: 'shraddha',
    name: 'Shraddha',
    kashmiri: 'श्राद्ध',
    category: 'Ancestral Ritual',
    description: 'Rituals for the departed souls, performed on death anniversaries and during Pitru Paksha.',
    purpose: 'To honor and provide peace to the souls of departed ancestors.',
    historicalBackground: 'KP Shraddha rituals follow the Kashmiri Shaiva tradition with specific mantras and procedures.',
    religiousSignificance: 'Nourishes the departed souls and ensures their peaceful journey in the afterlife.',
    materials: [
      'Til (sesame seeds)',
      'Water for tarpan',
      'Rice',
      'Seasonal fruits',
      'Sacred grass (kusha)',
      'Pinda (rice balls)',
    ],
    steps: [
      'Purification and fasting',
      'Invocation of ancestors',
      'Tarpan (water offering)',
      'Pinda Dan (rice ball offering)',
      'Brahmin feeding (bhojan)',
      'Prayers for ancestral peace',
    ],
    regionalVariations: 'Kashmiri Pandits perform Shraddha according to their specific sampradaya.',
    commonMisconceptions: 'Shraddha should not be confused with mourning — it is an act of love and gratitude.',
    icon: '🪷',
  },
  {
    id: 'havan',
    name: 'Havan (Yajna)',
    kashmiri: 'हवन',
    category: 'Vedic Ritual',
    description: 'Sacred fire ceremony performed for various purposes — purification, blessings, and offering to deities.',
    purpose: 'Purification of environment, seeking divine blessings, and fulfillment of specific intentions.',
    historicalBackground: 'Havan/Yajna is at the core of Vedic tradition and has been central to KP religious life.',
    religiousSignificance: 'Fire (Agni) is the medium through which offerings reach the divine. Agni is the witness to all sacred acts.',
    materials: [
      'Havan kund (fire pit)',
      'Ghee (clarified butter)',
      'Samidha (sacred wood)',
      'Samagri (herbal mixture)',
      'Til (sesame)',
      'Rice',
      'Mango wood',
      'Camphor',
    ],
    steps: [
      'Preparation of havan kund',
      'Invocation of Agni',
      'Sankalpa (statement of intention)',
      'Offering of ghee and samagri with mantras',
      'Main offerings',
      'Purnahuti (final offering)',
      'Aarti and prayers',
      'Distribution of prasad',
    ],
    regionalVariations: 'KP havans use specific Kashmiri Shaiva mantras and procedures.',
    commonMisconceptions: 'Havan is not just a ritual fire — it is a precise Vedic science with specific protocols.',
    icon: '🔥',
  },
];

// KP Wedding Timeline
export const KP_WEDDING_TIMELINE = [
  {
    stage: 'Pre-Wedding (Weeks Before)',
    ceremonies: [
      {
        name: 'Mangni / Rishta',
        description: 'Initial proposal and family approval',
        importance: 'high',
      },
      {
        name: 'Lagan',
        description: 'Formal engagement with exchange of Lagan Patra',
        importance: 'high',
      },
      {
        name: 'Muhurat Fixing',
        description: 'Consultation with Pandit for auspicious wedding date and time',
        importance: 'high',
      },
    ],
  },
  {
    stage: 'Day Before Wedding',
    ceremonies: [
      {
        name: 'Livun',
        description: 'Ritual purification and cleaning of the wedding venue',
        importance: 'high',
      },
      {
        name: 'Devgon',
        description: 'Propitiation of family deities and ancestors at both homes',
        importance: 'critical',
      },
      {
        name: 'Vara Chaturdashi',
        description: 'Groom\'s rituals the night before the wedding',
        importance: 'high',
      },
      {
        name: 'Mehendi',
        description: 'Henna application for the bride',
        importance: 'medium',
      },
    ],
  },
  {
    stage: 'Wedding Day — Morning',
    ceremonies: [
      {
        name: 'Pratah Puja',
        description: 'Morning prayers by both bride and groom\'s families',
        importance: 'high',
      },
      {
        name: 'Bridal Preparations',
        description: 'Dressing the bride in traditional Kashmiri attire',
        importance: 'high',
      },
      {
        name: 'Baraat Departure',
        description: 'Groom\'s procession to the venue',
        importance: 'medium',
      },
    ],
  },
  {
    stage: 'Wedding Day — Main Ceremony',
    ceremonies: [
      {
        name: 'Var Satkaar',
        description: 'Welcome of the groom\'s party',
        importance: 'high',
      },
      {
        name: 'Ganesh Puja',
        description: 'Prayer to remove obstacles',
        importance: 'critical',
      },
      {
        name: 'Hasta Milap / Panigrahana',
        description: 'Sacred joining of hands — the central ritual',
        importance: 'critical',
      },
      {
        name: 'Saptapadi',
        description: 'Seven steps around the sacred fire',
        importance: 'critical',
      },
      {
        name: 'Mangal Sutra',
        description: 'Tying of the sacred thread',
        importance: 'critical',
      },
      {
        name: 'Sindur Daan',
        description: 'Application of vermillion',
        importance: 'critical',
      },
    ],
  },
  {
    stage: 'Post-Wedding',
    ceremonies: [
      {
        name: 'Vidaai',
        description: 'Farewell ceremony for the bride',
        importance: 'high',
      },
      {
        name: 'Grih Pravesh',
        description: 'Bride\'s entry into the groom\'s home',
        importance: 'critical',
      },
      {
        name: 'Reception',
        description: 'Community celebration',
        importance: 'medium',
      },
    ],
  },
];
