// Kashmiri Pandit surname (kram) -> gotra(s).
//
// SOURCE: Compiled from the authoritative list at ikashmir.net/names/gotras.html
// ("Gotras of Kashmiri Pandits"). Kashmiri Brahmins are divided into ~199 exogamous
// gotras descended from Rishis; each family also carries a kram (nick-name / surname).
// One surname can appear under MANY gotras, so results list every gotra under which
// the surname is recorded. Confirm your actual gotra with family records / your purohit.

export interface SurnameGotra { surname: string; gotras: string[]; }

export const KP_SURNAME_GOTRA: SurnameGotra[] = [
  { surname: "Aima", gotras: ["Datthtreya (Koul)"] },
  { surname: "Amhardar", gotras: ["Pat Svamina Kaushika"] },
  { surname: "Babu", gotras: ["Datthtreya (Koul)"] },
  { surname: "Badam", gotras: ["Svamina Gautama"] },
  { surname: "Badgami", gotras: ["Deva Kucha Atreya"] },
  { surname: "Bakaya", gotras: ["Paladeva Vasgargya"] },
  { surname: "Bakhshi", gotras: ["Dar Varshaganya","Svamina Shandalya"] },
  { surname: "Bali", gotras: ["Svamina Bhargava"] },
  { surname: "Bamtsunt", gotras: ["Datthtreya (Koul)"] },
  { surname: "Bamzai", gotras: ["Datthtreya (Koul)"] },
  { surname: "Bandar", gotras: ["Kantha Dhaumyana Laugakshi Gautama"] },
  { surname: "Bangi", gotras: ["Dar Bharadwaja"] },
  { surname: "Bangru", gotras: ["Paladeva Vasgargya"] },
  { surname: "Barbuz", gotras: ["Varshayani"] },
  { surname: "Bataphalu", gotras: ["Deva Shandalya"] },
  { surname: "Battiv", gotras: ["Svamina Bhargava"] },
  { surname: "Bazari", gotras: ["Svamina Bharadvaja"] },
  { surname: "Bazaz", gotras: ["Svamina Gautama"] },
  { surname: "Bhan", gotras: ["Deva Gargya","Raj Bhut Logaskhi Deval"] },
  { surname: "Bhandari", gotras: ["Vasishta Svamina Maudgalya"] },
  { surname: "Bhatt", gotras: ["Svamina Koshk Bharadwaja","Dar Kapisthala","Dat Dat Shalan Kautsa","Deva Bharadwaja","Deva Gautama","Deva Kaushika","Kautsa Atreya","Kaushika Bhardwaja","Kanth Kasahap","Kash Aupamanyava","Mitra Shandalya","Nanda Koshk","Raj Dat Atreya Shalan Kautsa","Sharman Bharadwaja","Shandalya Bharadwaja","Sharman Kautsa","Svamina Shandalya","Svamina Vasishta Bharadwaja","Svamina Vatsya Aupamanyava","Wasishta"] },
  { surname: "Bhuni", gotras: ["Svamina Maudgalya"] },
  { surname: "Bindri", gotras: ["Wasadeva Palagargya"] },
  { surname: "Bira", gotras: ["Pat Svamina Kaushika"] },
  { surname: "Bradi", gotras: ["Deva Kashyap Maudgalya Kashyap","Dev Svamina Maudgalya"] },
  { surname: "Braru", gotras: ["Pat Svamina Kaushika"] },
  { surname: "Breth", gotras: ["Kantha Dhaumyana Laugakshi Gautama"] },
  { surname: "Buju", gotras: ["Datthtreya (Koul)"] },
  { surname: "Buni", gotras: ["Svamina Maudgalya"] },
  { surname: "Chacha", gotras: ["Pat Svamina Kaushika","Ratra Bhargava"] },
  { surname: "Chaghat", gotras: ["Pat Svamina Kaushika"] },
  { surname: "Chaka", gotras: ["Svamina Atreya"] },
  { surname: "Chakan", gotras: ["Svamina Gotam Gosh Vas Aupamanyava"] },
  { surname: "Chana", gotras: ["Svamina Maudgalya"] },
  { surname: "Chandra", gotras: ["Bhava Kapishthala"] },
  { surname: "Chandru", gotras: ["Karchanda Shandale"] },
  { surname: "Charangu", gotras: ["Svamina Gautama"] },
  { surname: "Chhotu", gotras: ["Svamina Gotam Laugakshi"] },
  { surname: "Chillum", gotras: ["Svamina Gautama"] },
  { surname: "Choku", gotras: ["Svamina Gotam Laugakshi"] },
  { surname: "Chothai", gotras: ["Svamina Warshaganya"] },
  { surname: "Choudhri", gotras: ["Artha Varshaganya Shandalya"] },
  { surname: "Chowdhri", gotras: ["Datthtreya (Koul)"] },
  { surname: "Dandar", gotras: ["Datthtreya (Koul)"] },
  { surname: "Dangar", gotras: ["Datthtreya (Koul)"] },
  { surname: "Dar", gotras: ["Dar Bharadwaja"] },
  { surname: "Dassu", gotras: ["Kanth Kasahap"] },
  { surname: "Deva", gotras: ["Deva Bharadwaja Kaushika"] },
  { surname: "Dewani", gotras: ["Svamina Maudgalya"] },
  { surname: "Dout", gotras: ["Datthtreya (Koul)"] },
  { surname: "Drabi", gotras: ["Datthtreya (Koul)"] },
  { surname: "Duda", gotras: ["Svamina Warshaganya"] },
  { surname: "Durani", gotras: ["Pat Svamina Kaushika"] },
  { surname: "Duru", gotras: ["Raj Shandalya"] },
  { surname: "Fata", gotras: ["Svamina Gautama Laugakshi"] },
  { surname: "Fehrist", gotras: ["Svamina Gautama"] },
  { surname: "Fotedar", gotras: ["Pat Svamina Kaushika"] },
  { surname: "Gadar", gotras: ["Deva Bharadwaja"] },
  { surname: "Gaddu", gotras: ["Sharman Atreya"] },
  { surname: "Gadwali", gotras: ["Svamina Atreya"] },
  { surname: "Gagar", gotras: ["Svamina Gautama"] },
  { surname: "Galikrapa", gotras: ["Svamina Maudgalya"] },
  { surname: "Ganju", gotras: ["Pat Svamina Kaushika"] },
  { surname: "Garyali", gotras: ["Svamina Bharadvaja"] },
  { surname: "Ghasi", gotras: ["Svamina Vas Atreya"] },
  { surname: "Gigu", gotras: ["Svamina Aupamanyava"] },
  { surname: "Giru", gotras: ["Bhuta Aupamanyava Shalan Kayana"] },
  { surname: "Gurut", gotras: ["Svamina Gautama"] },
  { surname: "Hak", gotras: ["Datthtreya (Koul)"] },
  { surname: "Hakachar", gotras: ["Raj Kaushika"] },
  { surname: "Hakim", gotras: ["Deva Gautama Laugakshi"] },
  { surname: "Handu", gotras: ["Mitra Kashyapa","Svamina Atreya","Svamina Vasishta Bharadwaja"] },
  { surname: "Hangal", gotras: ["Svamina Warshaganya"] },
  { surname: "Hapa", gotras: ["Atri Bhargaya"] },
  { surname: "Hastiwal", gotras: ["Kantha Dhaumyana Laugakshi Gautama"] },
  { surname: "Hukhu", gotras: ["Svamina Vasishta Bharadwaja"] },
  { surname: "Hukku", gotras: ["Dev Wasishta"] },
  { surname: "Jala", gotras: ["Pat Svamina Kaushika"] },
  { surname: "Jalali", gotras: ["Datthtreya (Koul)"] },
  { surname: "Jan", gotras: ["Svamina Bharadvaja"] },
  { surname: "Jatu", gotras: ["Deva Bharadwaja"] },
  { surname: "Jawansher", gotras: ["Dar Bharadwaja"] },
  { surname: "Jinsi", gotras: ["Datthtreya (Koul)"] },
  { surname: "Jogi", gotras: ["Dar Shandalya"] },
  { surname: "Jota", gotras: ["Datthtreya (Koul)"] },
  { surname: "Kachru", gotras: ["Dar Varshaganya","Pat Svamina Kaushika"] },
  { surname: "Kadalabuju", gotras: ["Paladeva Vasgargya"] },
  { surname: "Kak", gotras: ["Datthtreya (Koul)","Svamina Gautama","Deva Parashara"] },
  { surname: "Kakapuri", gotras: ["Svamina Gautama"] },
  { surname: "Kala", gotras: ["Svamina Atreya"] },
  { surname: "Kalla", gotras: ["Bhava Kapishthala"] },
  { surname: "Kallu", gotras: ["Deva Bharadwaja"] },
  { surname: "Kalpush", gotras: ["Deva Patsvamina Koshk"] },
  { surname: "Kalu", gotras: ["Pat Svamina Kaushika","Dev Aupamanyava","Svamina Bharadwaja Vas Atre"] },
  { surname: "Kandar", gotras: ["Svamina Maudgalya"] },
  { surname: "Kanth", gotras: ["Svamina Maudgalya"] },
  { surname: "Kar", gotras: ["Deva Kantha Kashyapa","Karchanda Shandale"] },
  { surname: "Karawani", gotras: ["Deva Shandalya"] },
  { surname: "Karihalu", gotras: ["Svamina Gotam Bharadwaja"] },
  { surname: "Karnel", gotras: ["Varshayani"] },
  { surname: "Kasab", gotras: ["Dat Dat Shalan Kautsa"] },
  { surname: "Kashgari", gotras: ["Rishi Kaushika"] },
  { surname: "Kasid", gotras: ["Svamina Warshaganya"] },
  { surname: "Kathju", gotras: ["Svamina Warshaganya"] },
  { surname: "Kaul", gotras: ["Datthtreya (Koul)"] },
  { surname: "Kav", gotras: ["Kantha Dhaumyana Laugakshi Gautama"] },
  { surname: "Kem", gotras: ["Dev Vishamitra Varshaganya"] },
  { surname: "Kemdal", gotras: ["Svamina Gotam Bharadwaja"] },
  { surname: "Keni", gotras: ["Datthtreya (Koul)","Svamina Gautama"] },
  { surname: "Khaibri", gotras: ["Bhava Kapishthala"] },
  { surname: "Khanakatu", gotras: ["Svamina Hasya Dvaseya"] },
  { surname: "Khar", gotras: ["Svamina Bharadvaja","Svamina Bharadwaja"] },
  { surname: "Khari", gotras: ["Dat Was"] },
  { surname: "Khashu", gotras: ["Dev Aupamanyava","Paladeva Vasgargya"] },
  { surname: "Khaumush", gotras: ["Dat Dat Shalan Kautsa"] },
  { surname: "Khazanchi", gotras: ["Svamina Maudgalya"] },
  { surname: "Khod", gotras: ["Raj Kaushika"] },
  { surname: "Khoru", gotras: ["Bhava Kapishthala"] },
  { surname: "Khosa", gotras: ["Svamina Gautama"] },
  { surname: "Khoshu. Kav", gotras: ["Paldeva Vasagargya"] },
  { surname: "Khurdi", gotras: ["Deva Bharadwaja","Pat Svamina Kaushika"] },
  { surname: "Kichlu", gotras: ["Paladeva Vasgargya"] },
  { surname: "Kissu", gotras: ["Datthtreya (Koul)"] },
  { surname: "Kokru", gotras: ["Paladeva Vasgargya"] },
  { surname: "Kotar", gotras: ["Ratra Varshaganya"] },
  { surname: "Kothdar", gotras: ["Datthtreya (Koul)"] },
  { surname: "Koul", gotras: ["Datthtreya (Koul)"] },
  { surname: "Koul (Kulin)", gotras: ["Svamina Rishi Kanya Gargya"] },
  { surname: "Kukru", gotras: ["Paldeva Vasagargya","Svamina Koshk Bharadwaja"] },
  { surname: "Kutsru", gotras: ["Svamina Bharadwaja"] },
  { surname: "Kyani", gotras: ["Pat Svamina Kaushika"] },
  { surname: "Labru", gotras: ["Svamina Gotam Shandalya","Svamina Kantha Kashyapa"] },
  { surname: "Labru Langer", gotras: ["Svamina Gautama"] },
  { surname: "Ladakhi", gotras: ["Datthtreya (Koul)"] },
  { surname: "Lala", gotras: ["Svamina Maudgalya"] },
  { surname: "Lange", gotras: ["Svamina Warshaganya"] },
  { surname: "Langer", gotras: ["Svamina Vasa Gargya"] },
  { surname: "Lattu", gotras: ["Bhava Kapishthala"] },
  { surname: "Lidi", gotras: ["Dar Kapisthala"] },
  { surname: "Machama", gotras: ["Svamina Gargya"] },
  { surname: "Madan", gotras: ["Svamina Maudgalya"] },
  { surname: "Mala", gotras: ["Paladeva Vasgargya"] },
  { surname: "Malik", gotras: ["Dat Dat Shalan Kautsa"] },
  { surname: "Malla", gotras: ["Paldeva Vasagargya"] },
  { surname: "Mam", gotras: ["Pat Svamina Kaushika","Paladeva Vasgargya"] },
  { surname: "Mandal", gotras: ["Datthtreya (Koul)"] },
  { surname: "Mantapuri", gotras: ["Deva Laugakshi"] },
  { surname: "Mantu", gotras: ["Kara Shandalya"] },
  { surname: "Manwotu", gotras: ["Svamina Gautama"] },
  { surname: "Mattu", gotras: ["Pat Svamina Kaushika","Ratra Vishwamitra Agastya"] },
  { surname: "Mazari", gotras: ["Svamina Maudgalya"] },
  { surname: "Mekhzin", gotras: ["Datthtreya (Koul)"] },
  { surname: "Meva", gotras: ["Dev Aupamanyava"] },
  { surname: "Mich", gotras: ["Dar Kapisthala Upamanuva"] },
  { surname: "Mirakhur", gotras: ["Paladeva Vasgargya"] },
  { surname: "Miskin", gotras: ["Svamina Bharadvaja"] },
  { surname: "Misri", gotras: ["Dar Bharadwaja","Pat Svamina Kaushika","Paladeva Vasgargya"] },
  { surname: "Miyan", gotras: ["Svamina Bharadvaja"] },
  { surname: "Mogal", gotras: ["Sharman Kautsa"] },
  { surname: "Mota", gotras: ["Dar Dev Shalan Kapi"] },
  { surname: "Moza", gotras: ["Datthtreya (Koul)"] },
  { surname: "Muhtasib", gotras: ["Datthtreya (Koul)","Kantha Dhaumyana Laugakshi Gautama"] },
  { surname: "Muj", gotras: ["Svamina Maudgalya"] },
  { surname: "Muki", gotras: ["Wardhatta Shalana Kucha"] },
  { surname: "Mukka", gotras: ["Shalan Kautsa Sharman Gusha Watsya Aupamanyava"] },
  { surname: "Munga", gotras: ["Paladeva Vasgargya"] },
  { surname: "Munshi", gotras: ["Svamina Bharadvaja"] },
  { surname: "Mushran", gotras: ["Svamina Maudgalya"] },
  { surname: "Muttu", gotras: ["Dar Dev Shalana Kaushika"] },
  { surname: "Nagari", gotras: ["Datthtreya (Koul)","Kaushika Bhardwaja"] },
  { surname: "Nakhasi", gotras: ["Ishwar Shandalya Kusha"] },
  { surname: "Naqib", gotras: ["Svamina Gautama"] },
  { surname: "Nari", gotras: ["Svamina Shandalya"] },
  { surname: "Padar", gotras: ["Datthtreya (Koul)"] },
  { surname: "Padi", gotras: ["Svamina Gan Kaushika"] },
  { surname: "Padora", gotras: ["Svamina Gautama"] },
  { surname: "Pahalwan", gotras: ["Datthtreya (Koul)"] },
  { surname: "Pandit", gotras: ["Pat Svamina Kaushika","Pat Svamina Deva Ratra Parwara","Deva Laugakshi","Dev Aupamanyava","Nanda Kaushika Bharadwaja","Vatsya Gusha Aupamanyava"] },
  { surname: "Panzu", gotras: ["Pat Svamina Kaushika"] },
  { surname: "Parikala", gotras: ["Dar Bharadwaja"] },
  { surname: "Parimu", gotras: ["Svamina Gautama"] },
  { surname: "Partazi", gotras: ["Raj Dhattatreya"] },
  { surname: "Pat", gotras: ["Paldeva Vasagargya"] },
  { surname: "Patar", gotras: ["Bhava Kapishthala Kaushika"] },
  { surname: "Peshen", gotras: ["Bhuta Was Aupamanyava Laugakshi"] },
  { surname: "Peshin", gotras: ["Bhuta Vatsya Aupamanyava"] },
  { surname: "Piala", gotras: ["Svamina Gautama"] },
  { surname: "Pir", gotras: ["Paldeva Vasagargya","Paladeva Vasgargya"] },
  { surname: "Pishen", gotras: ["Bhuta Aupamanyava Vatsya Laugakshi"] },
  { surname: "Purbi", gotras: ["Deva Gautama"] },
  { surname: "Put", gotras: ["Paladeva Vasgargya","Svamina Maudgalya"] },
  { surname: "Qandahari Thalatsur", gotras: ["Dar Bharadwaja"] },
  { surname: "Qazi", gotras: ["Svamina Gautama"] },
  { surname: "Raina", gotras: ["Dat Sharman Kantha Kashyapa","Svamina Gautama Atreya Shalan Kucha"] },
  { surname: "Rangateng", gotras: ["Wasishta"] },
  { surname: "Ratiz", gotras: ["Datthtreya (Koul)"] },
  { surname: "Raval", gotras: ["Ishwar Shandalya Kusha"] },
  { surname: "Razdan", gotras: ["Kantha Dhaumyana Laugakshi Gautama","Svamina Gautama","Dhaumyayana","Kanth Kasahap","Svamina Gotam Shandalya","Svamina Gotam Shalan Kucha Atreya","Svamina Maudgalya"] },
  { surname: "Sabani", gotras: ["Deva Bharadwaja"] },
  { surname: "Safaya", gotras: ["Dar Varshaganya","Dar Wasak Shandilya","Deva Varshaganya Shandilya"] },
  { surname: "Sahib", gotras: ["Datthtreya (Koul)"] },
  { surname: "Said", gotras: ["Mitra Svamina Kaushika Atreya"] },
  { surname: "Salman", gotras: ["Datthtreya (Koul)","Pat Svamina Kaushika"] },
  { surname: "Sapru", gotras: ["Dipat Saman Aupamanyava"] },
  { surname: "Sav", gotras: ["Sharman Kautsa"] },
  { surname: "Sazawul", gotras: ["Dat Varshaganya"] },
  { surname: "Shah", gotras: ["Kantha Dhaumyana Laugakshi Gautama"] },
  { surname: "Shair", gotras: ["Kantha Dhaumyana Laugakshi Gautama"] },
  { surname: "Shal", gotras: ["Svamina Atreya"] },
  { surname: "Shali", gotras: ["Dar Varshaganya"] },
  { surname: "Shanglu Sulu", gotras: ["Pat Svamina Kaushika"] },
  { surname: "Shargha", gotras: ["Datthtreya (Koul)"] },
  { surname: "Shoga", gotras: ["Datthtreya (Koul)"] },
  { surname: "Shopuri", gotras: ["Dev Wasishta"] },
  { surname: "Shora Taku", gotras: ["Svamina Maudgalya"] },
  { surname: "Shunglu", gotras: ["Raj Vasisht"] },
  { surname: "Sibbu", gotras: ["Bhava Kapishthala"] },
  { surname: "Sikh", gotras: ["Svamina Atreya"] },
  { surname: "Singhari", gotras: ["Datthtreya (Koul)"] },
  { surname: "Sopuri-Pandit", gotras: ["Paladeva Vasgargya"] },
  { surname: "Sultan", gotras: ["Datthtreya (Koul)"] },
  { surname: "Sum", gotras: ["Svamina Vasa Gargya"] },
  { surname: "Tangan", gotras: ["Kanth Kasahap"] },
  { surname: "Tarivala", gotras: ["Svamina Gautama"] },
  { surname: "Tava", gotras: ["Svamina Gautama"] },
  { surname: "Teng", gotras: ["Pat Svamina Kaushika"] },
  { surname: "Thakur", gotras: ["Bhuta Was Aupamanyava Laugakshi","Svamina Kaushika"] },
  { surname: "Thalatsur", gotras: ["Svamina Gautama"] },
  { surname: "Thapal", gotras: ["Svamina Gautama"] },
  { surname: "Thela", gotras: ["Sharman Kautsa"] },
  { surname: "Thogan", gotras: ["Deva Parashara"] },
  { surname: "Thusu", gotras: ["Svamina Was Atreya","Svamina Vas Atreya"] },
  { surname: "Tikku", gotras: ["Svamina Bharadvaja"] },
  { surname: "Tilwan Koul", gotras: ["Shalan Kautsa Sharman Gusha Watsya Aupamanyava"] },
  { surname: "Tota", gotras: ["Datthtreya (Koul)"] },
  { surname: "Trakari", gotras: ["Ratra Vishwamitra Vasishta"] },
  { surname: "Tritsha", gotras: ["Dar Bharadwaja"] },
  { surname: "Tritshal", gotras: ["Pat Svamina Kaushika"] },
  { surname: "Tshut", gotras: ["Dar Bharadwaja"] },
  { surname: "Tsrungu", gotras: ["Deva Vardhatta Shalan Kaushika"] },
  { surname: "Tsul", gotras: ["Svamina Gotam Atreya"] },
  { surname: "Tulsi", gotras: ["Deva Parashara"] },
  { surname: "Tur", gotras: ["Svamina Laugakshi"] },
  { surname: "Turi", gotras: ["Svamina Gotam Laugakshi"] },
  { surname: "Turki", gotras: ["Dar Bharadwaja"] },
  { surname: "Ugra", gotras: ["Datthtreya (Koul)"] },
  { surname: "Ukhlu", gotras: ["Dev Wasishta"] },
  { surname: "Unt", gotras: ["Pat Svamina Kaushika"] },
  { surname: "Uthu", gotras: ["Dar Bharadwaja"] },
  { surname: "Vangar", gotras: ["Dev Vishamitra Varshaganya"] },
  { surname: "Vantu", gotras: ["Bhava Kapishthala"] },
  { surname: "Variku", gotras: ["Bhava Aupamanyava"] },
  { surname: "Vashnavi", gotras: ["Pat Svamina Kaushika"] },
  { surname: "Vichari", gotras: ["Dar Bharadwaja"] },
  { surname: "Waguzari", gotras: ["Dar Bharadwaja"] },
  { surname: "Wallu", gotras: ["Svamina Vatsya Aupamanyava"] },
  { surname: "Wanchu", gotras: ["Pat Svamina Kaushika"] },
  { surname: "Wangani", gotras: ["Kantha Dhaumyana Laugakshi Gautama"] },
  { surname: "Wanikhan", gotras: ["Bhava Kapishthal Aupamanyava"] },
  { surname: "Wat", gotras: ["Kantha Dhaumyana Laugakshi Gautama"] },
  { surname: "Watal", gotras: ["Pat Svamina Deva Ratra Parwara","Svamina Kaushika"] },
  { surname: "Waza", gotras: ["Pat Svamina Kaushika","Svamina Vas Atreya"] },
  { surname: "Wufa", gotras: ["Pat Svamina Kaushika"] },
  { surname: "Yachh", gotras: ["Deva Bharadwaja","Deva Parashara"] },
  { surname: "Yechh", gotras: ["(Deva) Parashara"] },
  { surname: "Zadu", gotras: ["Bhava Kapishthala"] },
  { surname: "Zahi", gotras: ["Svamina Maudgalya"] },
  { surname: "Zalpari", gotras: ["Bhuta Was Aupamanyava Laugakshi"] },
  { surname: "Zamindar", gotras: ["Datthtreya (Koul)"] },
  { surname: "Zari", gotras: ["Kantha Dhaumyana Laugakshi Gautama","Svamina Gautama"] },
  { surname: "Zaru", gotras: ["Deva Bharadwaja","Rishi Kavigargya"] },
  { surname: "Zithu", gotras: ["Pat Svamina Kaushika"] },
  { surname: "Zitshoo", gotras: ["Ratra Bhargava"] },
  { surname: "Zitu", gotras: ["Svamina Maudgalya"] },
  { surname: "Zotan", gotras: ["Svamina Maudgalya"] },
];

// Loose phonetic variants so alternate spellings still match
// (e.g. Kachru/Kachroo, Tikku/Tikoo, Koul/Kaul, Mattu/Mattoo).
function variants(raw: string): string[] {
  const base = raw.toLowerCase().replace(/[^a-z]/g, "");
  const set = new Set<string>([base]);
  const transforms: ((s: string) => string)[] = [
    (s) => s.replace(/(.)+/g, "$1"),
    (s) => s.replace(/oo/g, "u"),
    (s) => s.replace(/ee/g, "i"),
    (s) => s.replace(/ou/g, "u"),
    (s) => s.replace(/au/g, "u"),
    (s) => s.replace(/h/g, ""),
  ];
  for (const t of transforms) set.add(t(base));
  let folded = base;
  for (const t of transforms) folded = t(folded);
  set.add(folded);
  return Array.from(set).filter(Boolean);
}

export function findGotraBySurname(query: string): SurnameGotra[] {
  const q = query.trim();
  if (!q) return [];
  const qv = variants(q);
  const score = (s: SurnameGotra): number => {
    const sv = variants(s.surname);
    for (const a of qv) for (const b of sv) {
      if (a === b) return 0;
      if (b.startsWith(a) || a.startsWith(b)) return 1;
      if (b.includes(a) || a.includes(b)) return 2;
    }
    return 99;
  };
  return KP_SURNAME_GOTRA.map((s) => ({ s, r: score(s) }))
    .filter((x) => x.r < 99)
    .sort((a, b) => a.r - b.r || a.s.surname.localeCompare(b.s.surname))
    .map((x) => x.s);
}
